# Generated by Django 6.0.7 on 2026-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionweb',
            options={'verbose_name': 'Configuración Web', 'verbose_name_plural': 'Configuraciones Web'},
        ),
        migrations.AlterModelOptions(
            name='tiposocio',
            options={'verbose_name': 'Tipo de Socio', 'verbose_name_plural': 'Tipos de Socio'},
        ),
        migrations.AddField(
            model_name='tiposocio',
            name='descripciondetiposocio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tiposocio',
            name='roltiposocio',
            field=models.CharField(default='miembro', max_length=50, unique=True, verbose_name='Rol del Socio'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='configuracionweb',
            table='ConfiguracionWeb',
        ),
        migrations.AlterModelTable(
            name='tiposocio',
            table='TipoSocio',
        ),
    ]
